### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by itzharshit** [animeshxd/pyromongo#2]
Hello,
I liked your work very much
Do you have any example bot on the usage of this library.
I have code and i am saving the session in memory but I want to save it in Mongodb, it will be a big help if you help me out to setup it
Here is the code

 ` client = Client(":memory:", API_ID, API_HASH, bot_token=phone, plugins={"root": "handlers"})
        await client.start() `

**Comment by animeshxd** [comment]
Actually I haven't used this library for a while, 

I am using this on my pet project,
https://github.com/animeshxd/brcbot/blob/59fdfb8f32bc9c4a45e74104b66d5c5bdcc92d61/bot/__main__.py#L36

Can you please try the introduction Example?
https://github.com/animeshxd/pyromongo#introduction


```python
from motor.motor_asyncio import AsyncIOMotorClient


client = Client(":memory:", API_ID, API_HASH, bot_token=phone, plugins={"root": "handlers"}) 

mongo = AsyncIOMotorClient("mongodb+srv://..")
database = mongo["youdatabasename"]
client.storage = MongoStorage(database, remove_peers=False) # use remove_peers=True to remove all peers on logout
# Override default storage with MongoStorage before starting the client 

await client.start()

```

**Comment by itzharshit** [comment]
Actually i am not understanding how it is actually working.
Like the example code you sent above will store the session in Mongo and retrieve it again whenever i run the code?
Just like it is currently doing in memory.

And one more thing will it save multiple session in same database?

**Comment by animeshxd** [comment]
Yes, you are right,

Program uses FileStorage or MemeoryStorage to manage the session
https://github.com/pyrogram/pyrogram/blob/efac17198b5fcaec1c2628c4bba0c288a4d617d4/pyrogram/client.py#L265

We can override the [Storage](https://github.com/pyrogram/pyrogram/blob/efac17198b5fcaec1c2628c4bba0c288a4d617d4/pyrogram/storage/storage.py#L24) interface to use our own implementation of storage class to manage session

**Comment by itzharshit** [comment]
Thank you so much for the information.
And just one more thing will it save multiple session in same database?

**Comment by animeshxd** [comment]
1 session on 1 database only is possible at this moment,

**Comment by itzharshit** [comment]
Okay got it thanks
